# Minecraft / Fabric Properties
minecraft_version=1.21.1
loader_version=0.16.10
loom_version=1.10.0-alpha.11

# Mod Properties
mod_version=1.5.0+1.21.1
common_version=1.5.0+1.21.1
maven_group=com.creeperconset
archives_base_name=creeperconset

# Dependencies
fabric_version=0.116.17+1.21.1
neoforge_version=21.1.211
